### ISSUE TITLE
Running browser tests

### ISSUE THREAD

**Issue by MichaelXavier** [purescript-contrib/pulp#11]
I'm wondering if there's a best practice we could build into `pulp test` that runs tests in a browser environment instead of just injecting it into node. I've got some DOM manipulation code I want to test and of course that stuff isn't available in node out of the box.

One way could be to still do it in node and use something like:

https://github.com/tmpvar/jsdom

You'd probably need your main function to specify any dependencies as you can see in the examples, and then it could execute the test suite inside of a `jsdom.env`. The other approach is to write a test runner and actually open a headless webkit with phantomjs or something and get your tests that way.

Would love to know your thoughts on this.

**Comment by bodil** [comment]
I'm wary of adding too much functionality to Pulp, but I'd be open to adding a command line argument for specifying the command to run tests with, and and argument that causes it to be fed a psc generated bundle instead of assuming CommonJS, which I think ought to get you compatible with just about any test runner, PhantomJS included.

**Comment by MichaelXavier** [comment]
I ended up using Karma. I agree this would probably be too much functionality. Feel free to close.

**Comment by bodil** [comment]
No, I think I want to add what I described anyway. :)
