### ISSUE TITLE
Pulp.Watch.action assumes the existence of …Path options.

### ISSUE THREAD

**Issue by damncabbage** [purescript-contrib/pulp#136]
Bit of a weird one, and I'll leave it to your collective opinion as to whether it's worth tackling, but:
- `Pulp.Watch.action` does a `getOption'` (non-optional getOption) for `srcPath`, `testPath` and `dependencyPath`, to give to whatever action is being watched.
- These options aren't available to the `dep` or `init` commands.

The way I found this was with this odd command:

``` sh
$ pulp --then 'say Done' dep install purescript-derp
Internal error in Pulp.Args.Get: Missing default value for option: srcPath
This is a bug. Please report it.
* ERROR: Internal error in Pulp.Args.Get: Missing default value for option: srcPath
bower                        ENOTFOUND Package purescript-derp not found
* ERROR: Subcommand terminated with exit code 1
```

From the user's point of view, the bug is that `--watch` is a command that can be used with everything, even when it really shouldn't be.

From the Pulp dev's point of view, the bug is that `Pulp.Watch` is making assumptions it really shouldn't.

**Comment by hdgarrood** [comment]
Ah, of course. I do think this is worth fixing, although it's not immediately obvious how.

The Pulp.Args.Get stuff is kind of gross. I only allowed myself to write it because it was no less safe than the previous JS version, but I want to refactor it somehow eventually. One approach could be to extract all use of it in modules like Pulp.Build, Pulp.Test etc into one bit that gets run before anything happens, and then the real action could take a record of options or something.

It's not clear if that is relevant to this problem, but it might be useful context.

**Comment by hdgarrood** [comment]
Maybe we should just error if you try to specify `--watch` with a command that doesn't make sense?

By the way, the command you wrote works for me, but if I add `--watch`, then it does break (in the same way).

**Comment by damncabbage** [comment]
Erg, sorry, I must have copied the wrong line. It should have included `--watch`, yes.
