### ISSUE TITLE
Ctrl-c kills pulp psci

### ISSUE THREAD

**Issue by jchayat** [purescript-contrib/pulp#176]
Originally opened an [issue](https://github.com/purescript/purescript/issues/1878) for purescript, but it seems to only happen when using `pulp psci`.

I'm using pulp 8.0.0 and psc version 0.8 on a Mac.

**Comment by hdgarrood** [comment]
How did you install `psc`? I want to make sure I'm using the exact same version of all the libraries `psc` depends on, if possible. Also, what version of node.js are you using?

**Comment by maddie927** [comment]
I just ran into this with the versions below.  Installed via npm, used in zsh.

Here was the line my cursor was in the middle of when I pressed ctrl+c:

```
> runAff throwException p[cursor] (connect roombaUrl)
>
psci: Interrupt
```

Pulp version 8.2.0
psc version 0.8.5.0 using /usr/local/bin/psc

**Comment by hdgarrood** [comment]
I don't know what's going on here, although I expect it has something to do with `psci` being a subprocess of the node.js process when you run `pulp psci`. Unfortunately the only way I can see to fix this right now is to find some way of being able to run `psci` directly, which doesn't seem easy.

**Comment by hdgarrood** [comment]
I'm going to close this for now since nothing has happened for a long time. My best guess as to what's causing this is an outdated version of Node &mdash; I've seen a few issues like this fixed by updating Node. If you encounter this and updating Node doesn't fix it, please feel free to reopen / open new issues.
