### ISSUE TITLE
Possibly should also have a .gitattributes file when initialising a new project

### ISSUE THREAD

**Issue by arafangion** [purescript-contrib/pulp#216]
Setting up a purescript project is nicely simple, though I had to familiarise myself somewhat with node.js as well. It's all working and got "Hello sailor!" - very pleasant!

I noticed that it nicely generates a default .gitignore file, which is fantastic.

However, it probably should generate a default .gitattributes file as well and set the eol so that line endings are always consistent.

**Comment by hdgarrood** [comment]
Hm, I'm not sure if this should be considered in scope for Pulp. Don't Windows users have their git configuration by default set up to checkout CRLF but checkin LF anyway, without needing a .gitattributes file?

**Comment by arafangion** [comment]
@hdgarrood Yes and no.  The default behaviour is inconsistent between cygwin and msys git, and it has caused problems for me.  Also, I noticed that Visual Studio (or perhaps Resharper?) is automatically generating a .gitignore and .gitattributes file when I start a project.

But honestly, I agree that it's maybe not quite in scope for Pulp - but I feel that if it generates a .gitignore file, it should also generate a .gitattributes file.

**Comment by hdgarrood** [comment]
The thing about the gitignore that Pulp generates is that it's there because you would create a gitignore with those entries in 95% of purescript projects, and most of the remaining 5% only need very minor modifications. More importantly (imo) though, the stuff in the .gitignore is specifically to do with purescript. What you're suggesting in this gitattributes file isn't really to do with purescript - so this is why I'm happy to generate a gitignore file, but I don't think generating a gitattributes file is the right approach. Looking at existing purescript repositories, very few of them use gitattributes files (and I know that there are people working on those repositories who do use Windows). I also think that configuring your Git installations globally with your preferred line ending settings is probably a better solution in your specific case.

**Comment by arafangion** [comment]
Fair point.
