### ISSUE TITLE
Explicit separation of remainder arguments

### ISSUE THREAD

**Issue by maddie927** [purescript-contrib/pulp#220]
This works:

```
» pulp build --no-psa --json-errors
* Building project in [...]
{"warnings":[],"errors":[]}
* Build successful.
```

This fails:

```
» pulp build --json-errors --no-psa
* Building project in [...]
Invalid option `--no-psa'

Usage: psc [FILE] [-o|--output ARG] [--no-tco] [--no-magic-do] [--no-opts]
           [-v|--verbose-errors] [-c|--comments] [--source-maps]
           [-p|--no-prefix] [--json-errors]

* ERROR: Subcommand terminated with exit code 1
```

This works:

```
» pulp build --include test --json-errors
* Building project in [...]
{"warnings":[],"errors":[]}
* Build successful.
```

This fails:

```
» pulp build --json-errors --include test
* Building project in [...]
Invalid option `--include'

Usage: psc [FILE] [-o|--output ARG] [--no-tco] [--no-magic-do] [--no-opts]
           [-v|--verbose-errors] [-c|--comments] [--source-maps]
           [-p|--no-prefix] [--json-errors]

* ERROR: Subcommand terminated with exit code 1
```

Versions:

```
Pulp version 9.0.1
psc version 0.9.1
```

**Comment by natefaubion** [comment]
I think this is by design (it stops parsing pulp arguments once it gets to one it doesn't recognize). FWIW, I agree this behavior is a somewhat unexpected, and I've been confused by it before.

**Comment by maddie927** [comment]
This section of the readme is relevant as well:

> Any unrecognised options appearing after any command specific options will be passed through to the compiler

"Any" makes it sound to me like a filter, not a select-until.  "After" makes sense once you know how it's actually behaving.

**Comment by hdgarrood** [comment]
The README does say this a little further down, to be fair:

> Take care, though, that such options should appear _after_ pulp's own command specific options.

I agree that this can be confusing, though. I think my preferred fix would be to separate pulp and subprocess options with a `--` so that there's no ambiguity; it's completely clear which options are supposed to go where. (I think this was @bodil's suggestion originally). This approach would also enable us to catch misspelt pulp command-specific options and exit with a helpful error message, instead of just sending them on to the relevant subprocess as we do now, which usually just produces a somewhat confusing error.

This would be a breaking change, unfortunately, but I think that's a price worth paying. I don't think I would want to support both the current style and the `--` style; I think it would be too confusing.

Can anyone see any problems with this?

**Comment by maddie927** [comment]
Definitely prefer that explicit approach!

**Comment by bodil** [comment]
That's worth a breaking change imo, it's confused enough people already.

**Comment by maddie927** [comment]
It also might make sense to either make it a warning for one version or provide an additional hint when unrecognized options are encountered such as, "Pulp no longer passes unrecognized args to `psc`.  Did you mean to include a `--` before `[unrecognized option]`?"

**Comment by texastoland** [comment]
Just hit this too. Agreed `npm run`'s approach would be intuitive or at least familiar.
