### ISSUE TITLE
Precompile FFI by default

### ISSUE THREAD

**Issue by texastoland** [purescript-contrib/pulp#226]
Would a PR be welcome that enables either Bublé or Babel by default (with the ability to switch Browserify transforms)? The motivating case was a discussion today that we're using `purescript-eff-functions` largely to alleviate the noise of not having arrows etc.

**Comment by hdgarrood** [comment]
I'm a bit reluctant, as it will create extra work to remove such support once es6 support does come the compiler itself (which AFAICT is going to happen, just a question of when). At least I'd like to explore the feasibility of something that works alongside Pulp as it is now, perhaps using the `--before` option; I guess you might have done this already?

**Comment by texastoland** [comment]
> once es6 support does come to the compiler itself (which AFAICT is going to happen, just a question of when).

I need to revisit that. Buy-in was the obstacle rather than implementation. But I don't believe that addresses FFI?

> perhaps using the `--before` option;

I don't find Pulp lacking any facility to integrate additional build steps. The motivating discussion was about standardizing FFI around modern JS so library authors need libraries like `eff-functions` (even though I'm working on such a library) for fewer use cases.

The thought originally occurred to me because of a comment you made about unsupported JS syntax in Pursuit packages (although I can't recall the context).

**Comment by hdgarrood** [comment]
I guess my position is that once the compiler starts producing ES6 modules, it will probably be much more obvious what the best approach for dealing with ES6 features like arrow functions in FFI modules should be.

I'm not keen on changing Pulp's defaults so that FFI files are preprocessed by default, sorry. There's so many options to choose from, and many of these have so many configuration options too, I think we could endlessly debate which one we use, and I'm really not interested in that. Also, I don't think I trust any preprocessor enough to be confident that it won't inadvertently create extra work for people who don't care about ES6 (which is something I definitely want to avoid).

I don't understand how `eff-functions` relates to this problem, though; how would standardising on ES6 in FFI modules reduce the need for it?

**Comment by texastoland** [comment]
> I'm not keen on changing Pulp's defaults

I know so I raised discussion first. I think @kika or @dkoontz reminded me of it yesterday.

> There's so many options to choose from, and many of these have so many configuration options too,

That's fundamentally why I recommended [Bublé](https://buble.surge.sh/guide/#command-line-options). It's a minimal subset of Babel, TS, ect. authored by the maintainer of Rollup. <q>Minimal</q> being the selling point along with Rollup since that's the use case for emitting ES6.

> I don't think I trust any preprocessor enough to be confident that it won't inadvertently create extra work for people who don't care about ES6

I'm not familiar with any issue…ever?

> how would standardising on ES6 in FFI modules reduce the need for it?

#### With `eff-functions`

This will be preaching to the choir…check out [`getItemImpl`](https://github.com/eskimor/purescript-localstorage/blob/d29d844a5ad32358f7e4feb4a147bbcce2e4db65/src/DOM/WebStorage/String.purs#L56-L57) in my recent refactor of `localstorage`:

``` purs
foreign import getItemImpl :: forall e. EffFn4 (storage :: STORAGE | e)
  (Maybe String) (String -> Maybe String) ForeignStorage String (Maybe String)
```

And [FFI](https://github.com/eskimor/purescript-localstorage/blob/d29d844a5ad32358f7e4feb4a147bbcce2e4db65/src/DOM/WebStorage/String.js#L12-L15):

``` js
exports.getItemImpl = function(nothing, just, storage, key) {
  var item = storage.getItem(key);
  return item == null ? nothing : just(item);
};
```

Now with my upcoming `oo-ffi` PR no FFI will be needed at all. But both solutions necessarily introduce indirection and varying performance penalties (`oo-ffi` via dynamic access and `eff-functions` via extra closures).

#### With curried functions

The primary use case for `eff-functions` is minimizing boilerplate. Compare the above with:

``` purs
-- practically the same
foreign import getItemImpl :: forall e
   . (Maybe String) -> (String -> Maybe String) -> ForeignStorage -> String
  -> Eff (storage :: STORAGE | e) (Maybe String)
```

And FFI:

``` js
// exorbitantly verbose
exports.getItemImpl = function(nothing) {
  return function(just) {
    return function(storage) {
      return function(key) {
        return function() {
          var item = storage.getItem(key);
          return item == null ? nothing : just(item);
        };
      };
    };
  };
};
```

#### With arrows

ES6 arrows in particular dispatch such boilerplate. Moreover it lowers the barrier of introducing more [modern] JS into an app (as opposed to a library). Multiple times on my last project I should've offloaded algorithms to FFI for pragmatism but hesitated to introduce another build step or write difficult to <q>reason about</q> ES5. Behold:

``` js
exports.getItemImpl = nothing => just => storage => key
  => () => maybe(nothing, just, storage.getItem(key));

// reused by keyImpl
const maybe = (nothing, just, nullable) => nullable == null ? nothing : just(nullable);
```

**Comment by hdgarrood** [comment]
I understand the appeal of Bublé, but I am not sufficiently confident that other Pulp users would agree with you that it's the right choice (if one even exists).

> I'm not familiar with any issue…ever?

I saw one where `psc` was producing warnings because the ES6 -> ES5 compiler someone was using was adding an extra identifier to each module and `psc` considered it unused; if you're making a library which you want to be warning-free and something like this happens, you now have to go and figure out what's going on, even if you don't care about ES6. Additionally, for me, the bar is higher than that; I want to be confident that such issues won't occur, and so not being aware of any issues isn't enough.

As an aside, regarding `eff-functions`, that's actually not what I would consider the primary use case. In my mind, its purpose is to shift the balance of boilerplate-y code so that as much as possible of it can go into the PureScript part of your program, where it can be type-checked, i.e. for me, the primary goal is safety, not convenience. I think it should still exist once we have ES6 everywhere.

**Comment by texastoland** [comment]
> I am not sufficiently confident that other Pulp users would agree with you that it's the right choice (if one even exists).

Would there be an effective broader forum: Twitter, mailing list (obviously I'm not active on a majority of communication channels)…?

> it's purpose is to shift the balance of boilerplate-y code so that as much as possible of it can go into the PureScript part of your program,

But ES6 negates the boilerplate by changing `,`s to `=>`s and largely negating `return`.

> I think it should still exist once we have ES6 everywhere.

I had this exact conversation with Isaac last week about whether there'd be overlap between his `oo-ffi` proposal and `eff-functions`. I don't disagree with you. But each chips at the reason we use the others.

**Comment by texastoland** [comment]
I should point out there's a real existing issue when people start pushing ES6 intentionally or otherwise. Are any of these issues negated by a flag or override?

**Comment by hdgarrood** [comment]
I think we'd probably post on the mailing list and then link to it from everywhere else if we wanted to solicit feedback, but I'd rather not invite that just yet, as even if we ignore the issue of selecting an ES6 -> ES5 compiler, there are enough other potential issues that I just don't think now is the right time for this.

Yes, I was about to mention the issue of libraries containing ES6 in their FFI modules; the answer is no, there's no good way of addressing that yet. We'd need per-library metadata, which we don't really have right now, and which might be painful to redesign if we don't get it more or less right the first time (and which should be designed with much wider considerations in mind than just this).

**Comment by texastoland** [comment]
> (and which should be designed with much wider considerations in mind than just this).

Fair. I thought there was an issue for that in the compiler? Could you link it and close (I couldn't find it)?

**Comment by hdgarrood** [comment]
There may well be, but I'm not particularly inclined to go hunting for it right now ;)

**Comment by bodil** [comment]
I don't think Pulp ought to be converting ES6 to ES5 by default, especially as I can't see an obvious way of achieving that other than compiling JS code from some FFI folder directly into the `src` folder for `psc` to find. That's much too obtrusive for a default solution.

I gave this some thought recently, and what I'd like to see, both as a stopgap for ES6 support in the compiler and as a compiler feature I could see other uses for, is to add a preprocessor stage to `psc`, so that you could do something like `psc --preprocess-ffi babel` where `babel` is an arbitrary executable the compiler can pipe an FFI file to on stdin and receive ES5 output on stdout, rather than just reading the file from the file system directly.

I imagine ES6 to ES5 is a common enough use case that Pulp ought to support it, given this mechanism, but as a command line option, not by default. The output code isn't always handled by `psc` the way the user might expect, in my experience, so you've got to be aware of what you're doing if you're going to use it.

**Comment by maddie927** [comment]
Ideally `psc` would support accepted features from ES6/7/8 and emit the same output.  Only a small subset actually need to be understood by the compiler.. most FFI code can be passed through to the output unchanged, so "understanding" something like object spread isn't really an issue.

Still though, that could be a ways off and it would certainly be nice to write code as though it worked that way in the short term.  Bublé seems ideal for that temporary use case since it is only transforming language syntax and not adding polyfills, but allowing any piping preprocessor would be even better.

**Comment by paf31** [comment]
How would this work with packaging libraries? Would you commit the source files as well as the build products (FFI files)? Otherwise, non-Pulp users wouldn't be able to build your library.

**Comment by texastoland** [comment]
> Otherwise, non-Pulp users wouldn't be able to build your library.

That sounds essentially like https://github.com/purescript/purescript/issues/1206#issuecomment-228923156. It would mean non-Pulp consumers need a build step besides `psc`. It also illuminates a fundamental weakness of depending on Bower relative to npm (not a solution either) which should probably be mentioned in purescript/purescript#631. There's no standard way to integrate build steps or their dependencies. In the case of working on Batteries I wanted to be able to run each package's tests with the dependencies I resolve. I'm not sure of the answer but it's a personal pain point (cf. https://github.com/bodil/pulp/issues/226#issuecomment-239702155 particularly the last paragraph) integrating with JS.

**Comment by bodil** [comment]
Standardising on `package.json` as a project file, at least with jspm's extensions, wouldn't be such a bad idea... that doesn't need to (and of course can't) imply npm.

**Comment by texastoland** [comment]
Makes sense. BTW thank for both @bodil's and @hdgarrood's feedback. I agree Pulp isn't the right place to address it. Closing here.
