### ISSUE TITLE
Value in non-Main module not included in the built, bundled and optimized JS

### ISSUE THREAD

**Issue by Bellarmine-Head** [purescript-contrib/pulp#247]
I asked the question on SO:- http://stackoverflow.com/questions/41793687/how-to-export-a-purescript-value-to-the-built-js-from-a-file-that-is-not-main-pu

...and it has been suggested that pulp may be excluding my value (that I want to appear in the output JavaScript) because it's not referenced by other PureScript code.  (But note that values in Main.purs that are also unreferenced by any PS code *do* appear in the built JS.)

Is this the case?

Is there a way to get my value that is not in Main.purs but in another file to appear in the build JS?

**Comment by hdgarrood** [comment]
Yes, this is the case, and this is by design. When you run `pulp build --optimize --to bundle.js`, Pulp will treat your `Main` module as the entry point by default, and it will remove all code that's not reachable from `Main`. If you want to include additional modules in the bundle, that's what the `--modules` option is for. For example, I think running `pulp build --optimize --to bundle.js --modules Foo,Bar` would include the modules `Foo` and `Bar` in your bundle in the way you want.

**Comment by Bellarmine-Head** [comment]
Thanks @hdgarrood - I had a feeling that `Main` was treated specially by design.  I'll try the `--modules` option tomorrow morning.

**Comment by Bellarmine-Head** [comment]
@hdgarrood: Yes; adding the `--modules Foo` option resolved this problem.  Thanks.

**Comment by hdgarrood** [comment]
I'm glad to hear it, thanks for the update. :)
