### ISSUE TITLE
Consider automatically generating local documentation on `pulp version`

### ISSUE THREAD

**Issue by chrisdotcode** [purescript-contrib/pulp#248]
In the past, we used to run `pulp docs`, add the doc to the package, and push it.

...Unfortunately, that's brittle. You could forget to run `pulp docs`, or even forget to push the doc changes with the code changes.

Fast-forward to the Pursuit era. Now, when you push, Pursuit generates your docs for you and puts them online.

...Unfortunately, that's brittle. There's no way to have local documentation for a project that you download - and setting up a local pursuit to track all of the modules in your project is not the most fun.

**Proposed solution**: Upon pulp version, before pushing to your git repo, have `pulp docs` (or `psc-package` /cc @paf31 @natefaubion @hdgarrood) generate your doc for you, and include it in the commit that bumps the version. This way, docs are always generated, and kept in sync both locally and on Pursuit.

@paf31 recommends going even further, and instead of just giving you local docs for the package, we can generate an entire static documentation tree like haddock does, and give the user the docs for all the dependencies that a packages uses (the package set), instead of just that one package.

Thoughts?

**Comment by hdgarrood** [comment]
I've started working on moving HTML rendering into the compiler so that `psc-docs` can generate HTML in the same way that Pursuit does. My hope is that after that's done, you only need to run `pulp docs` to have HTML docs generated for your package and all your dependencies with links and everything. I want to see how that pans out before considering adding code to `pulp` to handle this use case.

I'm also not really keen on including HTML docs in your git repo by default if we can avoid it (which I think we can).

**Comment by hdgarrood** [comment]
`pulp docs -- --format html` should cover this, so I'm closing.
