### ISSUE TITLE
Updates for 0.11

### ISSUE THREAD

**Issue by paf31** [purescript-contrib/pulp#264]
To track the few updates needed for 0.11 compatibility:

- Use the `purs` executable
- Use the new `purs publish` workflow (pass the `bower.json` file and output of `bower list --json --offline` as file arguments to `purs publish`)
- Update the initial project to the latest package versions

**Comment by natefaubion** [comment]
As a note, The `0.11` release of `node-purescript-bin` does not include the shims, and won't work with `pulp` until these changes are made.

**Comment by mbid** [comment]
As another note, `pulp init` sets `^3.0.0` as version for `prelude`, `console` and `psci-support`. `purescript-0.10.7` couldn't build these on my machine (something about `Effect` being defined both in `Prim` and in `Eff`). Downgrading to `^2.0.0` solved the problem. I don't know how far the next (compatible) release of `puresecript` on npm is away, but if it will likely take a while it would be cool if somebody could fix this so that noobs like me don't trip so much.

**Comment by danse** [comment]
I wonder whether is there a way to synchronise Pulp and the compiler, so that mismatches are easier to troubleshoot. Even a runtime warning like "This version of Pulp works with version x of the Purescript compiler, you are using version y" could save a lot of headaches for both users and maintainers. Maybe there is already an issue about that, sorry if i'm duplicating. I found some related conversation on #265

**Comment by hdgarrood** [comment]
Pulp does that already for minimum versions, but it's not really possible to predict in advance which future versions of purescript will necessitate updates to pulp.

**Comment by hdgarrood** [comment]
Resolved by #266.
