### ISSUE TITLE
Silent option on pulp build

### ISSUE THREAD

**Issue by Cmdv** [purescript-contrib/pulp#290]
It would be nice for a `--silent` for `pulp build` because in Travis builds like [this](https://travis-ci.org/slamdata/slamdata/jobs/248296070) end up with a massive output:
```
Compiling ...
Compiling ...
........
```

when really the part user is interested in is bellow or any compilation failures:
```
           Src   Lib   All
Warnings   0     0     0  
Errors     0     0     0  
* Build successful.
```

I know it has previously been bought up in https://github.com/purescript-contrib/pulp/issues/261 but wanted to make a _slightly_ stronger case for it 😋

**Comment by hdgarrood** [comment]
This is different from #261, #261 was only asking for the option to silence the messages generated by `pulp`. What you're asking for is a bit different as the "Compiling X" messages come from the compiler, and the errors, warnings, and summary come from the compiler through `psa` (if you're using it).

Since all of the "Compiling" lines come from the compiler, not pulp, the only way to do this in pulp would be to parse and selectively echo the output of the compiler, which I definitely do not want to do. I'd rather address this inside the compiler.

**Comment by Cmdv** [comment]
@hdgarrood ah yeah not a problem I wasn't entirely sure where these were being generated. I'll close it and open up an issue on the compiler 👍
