### ISSUE TITLE
Do not remove existing entries in .gitignore

### ISSUE THREAD

**Issue by koterpillar** [purescript-contrib/pulp#302]
I have a project that already has some files, including things in `.gitignore`. When running `pulp init --force`, it should not overwrite `.gitignore` but add the PureScript-specific entries to it. Ideally, `--force` shouldn't even be required if the only conflict is the `.gitignore` file.

**Comment by hdgarrood** [comment]
Sorry for the delay in responding. I'm not massively keen on this, because `pulp init` was never designed with the use case of being run in a directory which already has stuff inside it. If we add content-aware diffing and patching in the case of .gitignore files, wouldn't it be potentially surprising if we didn't do the same for all the other files we're generating automatically? (To clarify: I definitely do not want to implement or maintain that.)

If you're creating a purescript project as a sub-project of an existing repo, I'd recommend just running `pulp init` in a subdirectory instead.
