### ISSUE TITLE
Support npm packages

### ISSUE THREAD

**Issue by paldepind** [purescript-contrib/pulp#325]
Hello.

I have a JavaScript library that I want to add PureScript support to using the FFI. As far as I understand I have to supply these in a separate Bower package. This has several downsides:

* Users have to install two packages instead of just one
* These two packages may get out of sync because a Bower package can't specify a dependency on a specific version of an npm package. This can cause bugs.
* I have to maintain two packages on two separate package systems.

With TypeScript and Flow it is possible to put type declarations inside one's normal npm package. It would be nice if Pulp could do something similar.

Thanks a lot for your consideration. I apologize if this issue already exists but I couldn't find any.

**Comment by hdgarrood** [comment]
This is unfortunately not possible because of how npm handles dependencies. See http://harry.garrood.me/blog/purescript-why-bower/. There is also a lot of discussion on the compiler issue tracker.

**Comment by paldepind** [comment]
> See http://harry.garrood.me/blog/purescript-why-bower/

Please correct me if I'm wrong but the problem described in the blog post is partly solved by npm using peer dependencies. In the specific case in the blog post the `purescript-foo` should declare `purescript-maps` as a peer dependency. Then installing `purescript-foo` will never result in a duplicated install of `purescript-maps` and the run-time errors due to several version of the same package being installed won't happen.

But, note that I'm specifically concerned about the scenario where a PureScript FFI is written for an existing package on npm. In this case npm is going to be used no matter what. And using Bower alongside seems to introduce more problems than it solves. The dependency between the Bower package and the npm package is completely unenforced and unchecked by any tools. That seems quite unsafe to me.

How are you to know which version range of the npm package the Bower package depends on? What prevents you from accidentally updating the bower package without updating the npm package? If a new version of the npm package is released how do I know if it's safe to install it or if it's incompatible with the Bower package?

**Comment by hdgarrood** [comment]
Ok, yeah; it's possible that peer dependencies could address it, although I'm a little concerned that the default behaviour of npm is to not install them. It also depends on everyone remembering to actually use the peer dependencies fields in their package.jsons, which I think is likely to be a problem in practice. But do feel free to investigate that further. I'm going to leave this issue closed for now though, because I don't have the capacity to do this sort of investigation myself, and it's an issue that's wider than just Pulp anyway; I wouldn't want to build support for new dependency management workflows in to Pulp before they had been trialled elsewhere in the ecosystem to some extent.

> The dependency between the Bower package and the npm package is completely unenforced and unchecked by any tools. That seems quite unsafe to me.

Yes, indeed. The tools which would check this simply don't exist right now.

> How are you to know which version range of the npm package the Bower package depends on?

The author of the Bower package would need to document this.

> What prevents you from accidentally updating the bower package without updating the npm package?

Nothing, although you'll probably see runtime errors pretty quickly in most cases if you do this accidentally.

> If a new version of the npm package is released how do I know if it's safe to install it or if it's incompatible with the Bower package?

You don't. I guess you should read the changelog of the npm package, and look through the FFI bindings to see if you're using any parts of the npm package which have changed.

As you say, this state of affairs is obviously not ideal, but any use of the FFI sort of 'voids your warranty' anyway. If you want to avoid this kind of issue, the obvious solution is to do what Elm does and just not use packages which were originally written in JS.

**Comment by maddie927** [comment]
I wonder how Reason gets away with it.. https://redex.github.io/

**Comment by paldepind** [comment]
Thanks a lot for the detailed answer @hdgarrood. I apologize for the late reply (I read your message on the phone and then forgot about it).

> The author of the Bower package would need to document this.

My situation is exactly that I want to create PureScript bindings on Bower for a package on npm. So I'll be careful to document which versions of the npm package the bower package depends on.

> As you say, this state of affairs is obviously not ideal, but any use of the FFI sort of 'voids your warranty' anyway.

Ok, then it seems that we agree :smile: I definitely understand that changing the way packages are handled is quite an undertaking. And I'm certainly not knowledgeable or familiar enough with the PureScript ecosystem to know what would be the right way forward. But, I'll offer an idea anyway:

* Fork Bower and give it a new name.
* Make the Bower fork use a separate PureScript only repository.
* Make the Bower fork understand npm packages such that PureScript packages can depend safely on npm packages.

Forking Bower might sound crazy. But note that the last commit on Bower was _a half year_ ago. So keeping the fork up to date with upstream should be fairly easy as upstream is practically dead. 

The benefits of that approach includes:

* Building on top of Bower should reduce the amount of work necessary.
* Simply giving the Bower fork a new name will, in itself, be a huge PR benefit. JavaScript developers associate the name Bower with a deprecated package manager that died years ago. Having your own package manager is, on the other hand, quite cool.
* The interaction between PureScript packages and npm packages will be much much safer
* All PureScript packages can avoid the redundant `purescript-` prefix since the fork will use a new registry.
* It will be possibly to slowly add additional features to the fork that are specific to the PS language.

Anyway, that is just an idea.
