### ISSUE TITLE
Sort imports in all purs files

### ISSUE THREAD

**Issue by eviefp** [purescript-contrib/pulp#352]
Would anyone mind a PR that sorted all imports? When auto-adding imports via `psc-ide`, it seems to do a re-sort on (at least part of) the import list, which makes it harder to read diffs.

If yes, what about open imports? Would anyone mind adding a list of imported stuff from each?

**Comment by hdgarrood** [comment]
I can see why this would be nice, but I would prefer to keep the project-local imports separate from the imports of modules from other packages.

**Comment by hdgarrood** [comment]
Actually yeah, I'd be happy to sort all the imports so that ide plugins don't mess with them. In fact it looks like we're going to get this as part of #360. Incidentally I've also changed my mind about open imports: it probably would be better to only have one open import (i.e. of `Prelude`) per module.
