### ISSUE TITLE
Lua backend

### ISSUE THREAD

**Issue by DoctorRainer** [purescript-contrib/pulp#387]
Is it possible to use something like https://github.com/lua-purescript/purescript with pulp?

**Comment by hdgarrood** [comment]
I doubt it - it looks like this repo was forked from the main compiler a long time ago, so the CLI of the current parser and this fork might have diverged; pulp only supports 0.11.0 and higher, but from what I can tell that fork is pre-0.11.0 (i.e. it has separate executables `psc`, `psc-docs`, `psci`; I think it was 0.11.0 when we combined all of these into a single `purs` executable). You may be able to use an old version of pulp with lua-purescript, but I doubt it will be worth the effort - you'll also have to use old versions of libraries and everything too; the ecosystem has moved on quite a bit since then.

The more modern alternate backends use the `--dump-corefn` flag to dump an intermediate representation as JSON, and then have separate programs to compile that into the desired output format, so that you don't need to maintain a compiler fork. Those definitely work with pulp, as you're still using the standard `purs` executable.
