### ISSUE TITLE
0.7 FFI interaction with non-purescript bower dependencies

### ISSUE THREAD

**Issue by ghost** [purescript-contrib/pulp#43]
Maybe I am just being paranoid, but it seems like https://github.com/bodil/pulp/commit/65c3c6b7d702c9f1b42d9440e362fb054fba3f2a#diff-f9ab28ae135f8c6a15981c24670cc941R9 might be too ambiguous of a convention. I can imagine that other bower dependencies that rely on other compilers might have components that match that pattern, and those files would inadvertently get copied/baked into psc output with strange hard to debug results.

Supposing that it actually is a problem, I propose that the convention needs to change to something like `bower_components/*/src/**/*.purs.js`

**Comment by bodil** [comment]
You're right, the current convention seems a bit risky. @paf31?

**Comment by paf31** [comment]
For this to cause problems, I think all of the following have to hold:
1. A module is called `purescript-something` in `bower_components`
2. That module has a `.js` file under `src/`
3. That JS files has a magic `// module ...` comment (otherwise the compiler won't accept it as an FFI module anyway, and you'll get an error early on in the compilation process)

I would say this would be rare enough to not worry, but I'm happy to discuss alternatives.

It might be a good idea for the compiler to warn and continue, instead of raising an error, when 3) holds though.

**Comment by garyb** [comment]
@paf31 re: 1, the glob doesn't mention `purescript-`, so that's probably the only problem here.

**Comment by paf31** [comment]
Oops, I see. Yes, that should definitely be there.

I'll send a PR.

**Comment by paf31** [comment]
We are, of course, trading one global convention for another here, but I think this one (dependencies being called `purescript-something`) is more likely to be used in practice.

**Comment by garyb** [comment]
Very true. I quite like the idea of `.purs.js` too, shame we didn't do that already in the core libraries.

**Comment by bodil** [comment]
I agree, `.purs.js` would be the cleanest solution here. Requiring PS packages to always be called `purescript-`something is a bit iffy, but it's probably a convention that's entirely valid right now, so let's go with it until it starts causing trouble.

**Comment by paf31** [comment]
I think the problem is that the compiler tries to be entirely conventionless, whereas `pulp` tries to do the exact opposite, so at some point, it's naturally going to run into the need for global conventions. Arguably it already has: the compiler doesn't enforce that PureScript source files be called `*.purs`, but it's a global convention which everyone has adopted.
