### ISSUE TITLE
Use webpack instead of browserify

### ISSUE THREAD

**Issue by codygman** [purescript-contrib/pulp#45]
I started using pulp and browserify recently and have noticed that browserify is kind of slow. At least, I'm pretty sure it could be faster at what it does by doing incremental builds.

I saw online that [webpack](http://webpack.github.io/) did incremental builds and does the same thing browserify does.

Thoughts on using webpack? I'm new to frontend stuff, so I'm not sure if there's a hidden advantage to browserify.

Thanks

**Comment by bodil** [comment]
Initially, I've been using Browserify because it's simple and requires no configuration. I meant to extract it as a plugin once I had a plugin system in place, but it's proving to be rather a fundamental feature, so I'll probably keep it in the core.

I've got some PS projects building with Webpack, and the improvement is quite considerable, but so is the level of configuration needed. I think I'll keep Browserify as the default because of this, but I'll definitely be adding some sort of Webpack capability to Pulp in the future - probably only after adding a plugin system, because Webpack has a considerable dependency graph that I'm not keen on inflicting on every Pulp user.

Browserify has some facility for doing incremental builds too, which might be worth investigating, but right now Pulp's watch mechanism doesn't even support that sort of thing.

**Comment by stkb** [comment]
If you're all-in on front-end development I agree webpack is a better tool although yes I agree it does come with a lot of baggage and configuration.

@codygman you may want to look at the [purs-loader](https://www.npmjs.com/package/purs-loader). With this you can use webpack as your build/watch tool which in turn uses the purs-loader to compile your purescript files. I've done in this in mixed js/purs projects and it works well.

**Comment by bodil** [comment]
I think I'll close this one now, as `pulp browserify` got support for incremental builds. I'd rather leave direct Webpack support for when there's a plugin architecture.

**Comment by codygman** [comment]
Oooh, I'll have to try out the incremental build support. That's really the
only reason I wanted to tryout webpack anyway :P
