### ISSUE TITLE
pulp build much slower than psc

### ISSUE THREAD

**Issue by user471** [purescript-contrib/pulp#51]
psc "bower_components/purescript-_/src/__/_.purs" "src/**/*.purs"  --ffi "src/**/_.js" --ffi "bower_components/purescript-_/src/*_/_.js"
~2 second
pulp build 
~10 seconds
I noticed the difference when I added bunch of dependencies
    "purescript-functions": "~0.1.0",
    "purescript-control": "~0.3.0",
    "purescript-foldable-traversable": "~0.4.0",
    "purescript-exceptions": "~0.3.0",
    "purescript-transformers": "~0.6.1"

**Comment by stkb** [comment]
I noticed the same, and it's because of this: Pulp first looks for all `.purs` and `.js` files, and then runs a very long `psc` command with each file as a separate argument (this was necessary to support all platforms, before psc itself supported file glob patterns as args). Now for some reason, when running `psc` with a ton of arguments, it takes a lot of time to process them, compared to if you run `psc` with globs as arguments (as in your first example).

If you run the same psc command that pulp creates, it takes just as long as a pulp build. Similarly, if you modify pulp to run `psc` with glob args instead then it's just as fast as your psc example.

I'm not sure why `psc` is so slow when lots of args are passed to it, but now that it supports globs as arguments, I think pulp should be modified to pass the glob patterns straight to psc instead. Also, the other purescript tools, `psc-bundle` and `psci` will soon support globs as arguments too, so hopefully eventually all the globbing code can be removed from pulp.
